import Head from "next/head";
import Image from "next/image";
import ProjectCard from "../components/ProjectCard";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [scrollY, setScrollY] = useState(0);
  let scrollH;
  if (typeof window !== "undefined") {
    console.log("You are on the browser");
    scrollH = document.body.scrollHeight;
    console.log(scrollY);
  } else {
    console.log("You are on the server");
  }

  Number.prototype.map = function (in_min, in_max, out_min, out_max) {
    return (
      ((this - in_min) * (out_max - out_min)) / (in_max - in_min) + out_min
    );
  };

  useEffect(() => {
    // console.log(scrollHeight)
  }, [scrollY]);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div class="px-6 pt-8 pb-20 relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-12 gap-6">
        <p className="text-base fixed text-white">Joseph Zhang</p>

        <p
          // style={{ opacity: scrollY.map(0, 90, 100, 0) * 0.01 }}
          className={`${
            scrollY > 10 ? "translate-y-[20px] opacity-0" : ""
          } sticky top-[2rem] text-base grid col-start-3 col-end-7 text-[rgb(255,255,255)] transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)]`}
        >
          I'm a designer interested in all things related to digital toolmaking,
          multimodal interaction, and systems thinking. I believe good design
          reflects artistic values focused around emotion and play. I’m a fourth
          year undergrad at Carnegie Mellon studying Communication Design and
          Human-Computer Interaction
        </p>

        <p
          className={`${
            scrollY > 10 ? "translate-y-[20px] opacity-0" : ""
          } sticky top-[2rem] text-base grid col-start-7 col-end-11 text-[rgb(255,255,255)] transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)] mb-16`}
        >
          In the past, I worked at Apple, Metalink, Brain Technologies, and
          Elevation Church. I’m currently a front-end developer at the
          Computational Creativity Lab. After graduation, I’ll be joining Skiff
          full-time to work on privacy-centric collaboration tools. If you have
          an interesting idea, let’s get in touch.
        </p>

        <ProjectCard col={1} image={"/project-covers/apple.jpg"}></ProjectCard>
        <ProjectCard col={2} image={"/project-covers/aiga-2.jpg"}></ProjectCard>
        <ProjectCard
          col={1}
          image={"/project-covers/elevation-connect.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={2}
          image={"/project-covers/natural.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={1}
          image={"/project-covers/elevation-connect.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={2}
          image={"/project-covers/natural.jpg"}
        ></ProjectCard>
      </main>

      <footer
        className={`left-0 w-full mix-blend-difference fixed bottom-0 grid text-white grid-cols-12 gap-6 px-6 py-4`}
      >
        <p className="col-start-3">Resume</p>
        <p className="col-start-7">LinkedIn</p>
        <p className="col-start-11">Twitter</p>
      </footer>
    </div>
  );
}
