import Head from "next/head";
import Image from "next/image";
import ProjectCard from "../components/ProjectCard";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [scrollY, setScrollY] = useState(0);

  Number.prototype.map = function (in_min, in_max, out_min, out_max) {
    return (
      ((this - in_min) * (out_max - out_min)) / (in_max - in_min) + out_min
    );
  };

  useEffect(() => {
    console.log(scrollY);
  }, [scrollY]);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="px-6 pt-8 pb-20 relative">
      <Head>
        <title>Joseph is a designer.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/liy8bpw.css"
        ></link>
      </Head>

      <main className="grid grid-cols-12 gap-6">
        <img
          src={"/zhang-icon.svg"}
          className={`${
            scrollY > 200
              ? "bg-[rgba(0,0,0,.8)]"
              : "bg-[rgba(255,255,255,.05)] "
          } w-16 h-16 fixed z-10 text-white rounded-sm p-4 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)]`}
        />

        <p
          className={`${
            scrollY > 40 ? "opacity-0" : ""
          } sticky top-[2rem] pt-2 grid mt-24 md:m-0 col-start-1 col-end-13 md:col-start-5 md:col-end-13 lg:col-start-5 lg:col-end-9 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)]`}
        >
          I'm Joseph, a designer interested in all things related to digital
          toolmaking, multimodal interaction, and systems thinking. I believe
          good design reflects artistic values focused around emotion and play.
          I’m a fourth year undergrad at Carnegie Mellon studying Communication
          Design and Human-Computer Interaction
        </p>

        <p
          className={`${
            scrollY > 40 ? "opacity-0" : ""
          } sticky top-[2rem] pt-2 grid col-start-1 col-end-13 md:col-start-5 md:col-end-13 lg:col-start-9 lg:col-end-13 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)] mb-16`}
        >
          In the past, I worked at Apple, Metalink, Brain Technologies, and
          Elevation Church. I’m currently a front-end developer at the
          Computational Creativity Lab. After graduation, I’ll be joining Skiff
          full-time to work on privacy-centric collaboration tools. If you have
          an interesting idea, let’s get in touch.
        </p>

        <ProjectCard
          col={1}
          isImage={true}
          content={"/project-covers/apple.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={2}
          isImage={true}
          content={"/project-covers/aiga-2.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={1}
          isImage={true}
          content={"/project-covers/elevation-connect.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={2}
          isImage={true}
          content={"/project-covers/natural-2.jpg"}
        ></ProjectCard>
        <ProjectCard
          col={1}
          isImage={false}
          content={"/project-covers/pixel-push.mp4"}
          placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
        ></ProjectCard>
        <ProjectCard
          col={2}
          isImage={false}
          content={"/project-covers/reading-trends.mp4"}
          placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
        ></ProjectCard>
        <ProjectCard
          col={1}
          isImage={false}
          content={"/project-covers/thinkspace.mp4"}
          placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
        ></ProjectCard>
      </main>

      <footer
        className={`left-0 w-full mix-blend-difference fixed bottom-0 grid text-white grid-cols-12 gap-6 px-6 py-4`}
      >
        <p className="col-start-1 col-end-5 opacity-20 hidden md:inline">
          Last updated April 23, 2022
        </p>
        <a
          target="_blank"
          href="/josephzhang-resume.pdf"
          className="col-start-1 md:col-start-5"
        >
          Resume
        </a>
        <a
          target="_blank"
          href="https://www.linkedin.com/in/josephzme/"
          className="col-start-3 md:col-start-7"
        >
          LinkedIn
        </a>
        <a
          target="_blank"
          href="https://twitter.com/__joz"
          className="col-start-5 md:col-start-9"
        >
          Twitter
        </a>
        <a
          target="_blank"
          href="mailto:jxsephz@gmail.com"
          className="col-start-7 md:col-start-11"
        >
          jxsephz@gmail.com
        </a>
      </footer>
    </div>
  );
}
