import Head from "next/head";
import Image from "next/image";
import ProjectCard from "../components/ProjectCard";
import React, { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1 },
};

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
  },
};

export default function Home() {
  const [scrollY, setScrollY] = useState(0);

  Number.prototype.map = function (in_min, in_max, out_min, out_max) {
    return (
      ((this - in_min) * (out_max - out_min)) / (in_max - in_min) + out_min
    );
  };

  useEffect(() => {
    console.log(scrollY);
  }, [scrollY]);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <AnimatePresence>
      <motion.div className="px-6 pt-8 pb-20 relative">
        <Head>
          <title>Joseph is a designer.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.jpg" />
          <link
            rel="stylesheet"
            href="https://use.typekit.net/liy8bpw.css"
          ></link>
        </Head>

        <motion.main
          variants={container}
          initial="hidden"
          animate="show"
          exit={{ opacity: 0 }}
          className="grid grid-cols-12 gap-6"
        >
          <motion.img
            variants={item}
            src={"/zhang-icon-white.svg"}
            className={`${
              scrollY > 200
                ? "bg-[rgba(50,50,50,.8)]"
                : "bg-[rgba(255,255,255,.05)]"
            } w-[64px] h-[64px] col-start-1 col-end-3 p-3 fixed z-10 text-[rgba(255,255,255,.9)] rounded-sm p-2 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)]`}
          />

          <motion.p
            variants={item}
            className={`${
              scrollY > 40
                ? "text-[rgba(0,0,0,0)]"
                : "text-[rgba(255,255,255,.9)]"
            }  sticky top-[2rem] pt-2 grid mt-24 md:m-0 col-start-1 col-end-13 md:col-start-5 md:col-end-13 lg:col-start-5 lg:col-end-9 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)]`}
          >
            I'm a designer interested in all things related to digital
            toolmaking, multimodal interaction, and systems thinking. I believe
            good design reflects artistic values focused around emotion and
            play. I’m a fourth year undergrad at Carnegie Mellon studying
            Communication Design and Human-Computer Interaction
          </motion.p>

          <motion.p
            variants={item}
            className={`${
              scrollY > 40
                ? "text-[rgba(0,0,0,0)]"
                : "text-[rgba(255,255,255,.9)]"
            } sticky top-[2rem] pt-2 grid col-start-1 col-end-13 md:col-start-5 md:col-end-13 lg:col-start-9 lg:col-end-13 transition duration-[300ms] ease-[cubic-bezier(0.22, 1, 0.36, 1)] mb-16`}
          >
            In the past, I worked at Apple, Metalink, Brain Technologies, and
            Elevation Church. I’m currently a front-end developer at the
            Computational Creativity Lab. After graduation, I’ll be joining
            Skiff full-time to work on privacy-centric collaboration tools. If
            you have an interesting idea, let’s get in touch.
          </motion.p>

          <ProjectCard
            title="Apple"
            description="Multimodal interaction"
            animation={item}
            col={1}
            isImage={true}
            content={"/project-covers/apple.jpg"}
          ></ProjectCard>
          <ProjectCard
            title="AIGA&Hue"
            description="Interactive data vis"
            animation={item}
            col={2}
            isImage={true}
            content={"/project-covers/aiga-2.jpg"}
          ></ProjectCard>
          <ProjectCard
            title="Elevation Connect"
            description="Web app"
            animation={item}
            col={1}
            isImage={true}
            content={"/project-covers/elevation-connect.jpg"}
          ></ProjectCard>
          <ProjectCard
            title="Brain Technologies"
            description="Multimodal interaction"
            animation={item}
            col={2}
            isImage={true}
            content={"/project-covers/natural-2.jpg"}
          ></ProjectCard>
          <ProjectCard
            title="Pixel Push"
            description="Multiplayer painting experience"
            animation={item}
            col={1}
            isImage={false}
            content={"/project-covers/pixel-push.mp4"}
            placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
          ></ProjectCard>
          <ProjectCard
            title="Reading Trends"
            description="Interactive datavis, NYT API"
            animation={item}
            col={2}
            isImage={false}
            content={"/project-covers/reading-trends.mp4"}
            placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
          ></ProjectCard>
          <ProjectCard
            title="Thinkspace"
            description="speculative VUI exploration"
            animation={item}
            col={1}
            isImage={false}
            content={"/project-covers/thinkspace.mp4"}
            placeholder={"/project-covers/thinkspace-placeholder.jpeg"}
          ></ProjectCard>
        </motion.main>

        <footer
          className={`left-0 w-full mix-blend-difference fixed bottom-0 grid text-[rgba(255,255,255,.9)] grid-cols-12 gap-6 px-6 py-4`}
        >
          <p className="col-start-1 col-end-5 opacity-20 hidden md:inline">
            Last updated April 23, 2022
          </p>
          <a
            target="_blank"
            href="/josephzhang-resume.pdf"
            className="col-start-1 md:col-start-5"
          >
            Resume
          </a>
          <a
            target="_blank"
            href="https://www.linkedin.com/in/josephzme/"
            className="col-start-3 md:col-start-7"
          >
            LinkedIn
          </a>
          <a
            target="_blank"
            href="https://twitter.com/__joz"
            className="col-start-5 md:col-start-9"
          >
            Twitter
          </a>
          <a
            target="_blank"
            href="mailto:jxsephz@gmail.com"
            className="col-start-7 md:col-start-11"
          >
            jxsephz@gmail.com
          </a>
        </footer>
      </motion.div>
    </AnimatePresence>
  );
}
